// <auto-generated />
using System;
using FplTool.Modules.Picks.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FplTool.Modules.Picks.Migrations
{
    [DbContext(typeof(PicksDbContext))]
    partial class PicksDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("FplTool.Modules.Picks.Domain.CaptainPick", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<int>("FplPlayerId")
                        .HasColumnType("int");

                    b.Property<int>("GameweekId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PickedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PlayerWebName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("PointsScored")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("GameweekId");

                    b.HasIndex("UserId", "GameweekId")
                        .IsUnique();

                    b.ToTable("picks_captain_picks", (string)null);
                });

            modelBuilder.Entity("FplTool.Modules.Picks.Domain.GameweekPointsSync", b =>
                {
                    b.Property<int>("GameweekId")
                        .HasColumnType("int");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastSyncedUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("GameweekId");

                    b.ToTable("picks_gw_points_sync", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
